### ISSUE TITLE
update sign convention and validation criteria in shear-shear test

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#116]
@patricialarsen (cc @EiffL) following the update to the  shear sign convention in the GCRCatalogs (see 
https://github.com/LSSTDESC/gcr-catalogs/pull/111) we should make sure the shear-related tests also follow the same convention (that is, the treecorr/GalSim convention). 

We need to, for example, remove the minus sign in 
https://github.com/LSSTDESC/descqa/blob/master/descqa/shear_test.py#L172
https://github.com/LSSTDESC/descqa/blob/master/descqa/shear_test.py#L273 
(and maybe other places; I haven't done an extensive check).

**Comment by yymao** [comment]
I tried to address this issue in the branch [issue/116/shear-sign-convention](https://github.com/LSSTDESC/descqa/tree/issue/116/shear-sign-convention) ([see diff here](https://github.com/LSSTDESC/descqa/compare/issue/116/shear-sign-convention)). 

However, after I started, I then realized I didn't know how to fix the theory prediction part of the code. [Here's a test run on this branch](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-06-10&test=shear&right=2018-06/2018-06-10/shear/summary.png), you can see the theory prediction is still in the old convention. 

At the same time I realized that the catalog still passed this test! Even though we don't need to striengent criteria, I think at a minimum the catalog should fail this test if the shear sign convention is wrong...

@patricialarsen, can you pick up from here and address these issues? Thanks! (Also, it would be great if you can add your GitHub username to DESC database so that I can assign this issue to you.)

(cc @EiffL @rmandelb)

**Comment by patricialarsen** [comment]
@yymao I'm waiting on covariance matrices to properly fix the validation question so we may as well wait for that before incorporating the sign convention into the validation. At the moment it's set up to only validate on the ++ term which is unaffected by the sign. 

Can we not simply not change the main part of the validation tests and instead read in shear_2_phosim? That's probably easier than remembering to change signs everywhere... 

But yes, I need to do some extra changes on the code anyway so no problem to make these changes.

**Comment by yymao** [comment]
@patricialarsen we can also do that (reading in `shear_2_phosim`), but there were some arguments about using treecorr convention. 

Anyway, sounds good that you'll take care of this when you update this test. Thanks!
