### ISSUE TITLE
bug in dN/dz test: normalizations, errorbars

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/descqa#117]
This issue is for some bugs (at least two) in the dN/dz test.  @yymao and I have been discussing this on slack, but it needs a bit more digging, so we agreed to open an issue (currently assigned to the two of us).

At the DC2 telecon today it was clear that the errorbars on the dN/dz test were wrong (an order of magnitude larger than the scatter in the data points).  Yao and I identified a few things going on:

- This is not a bug, but simply misuse of the test: the latest runs were trying to set the number of z bins using the wrong parameter, so it wasn't getting set (it was setting `Nbins` when it should have been `N_zbins`).  The configuration being used was such that the errorbar determination could not be particularly stable -- it should be the case that number of jackknife regions > number of data points.  This was not the case with the settings that were being used.  He and I have since been exploring use of 15 regions and 8 redshift bins, which should be more stable.

- One bug is that when `normed=True`, the errorbars have some problems (see run [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-06-08_2&test=Nz_r_DEEP2_JAN&right=2018-06/2018-06-08_2/Nz_r_DEEP2_JAN/config.yaml) with the above configuration issues fixed).  I suspect the histogram normalization scheme may be inconsistent between the jackknife calculation and the overall histogram, which would cause the covariance to be misestimated.

- Another bug is that when `normed=False`, the data and sims have inconsistent histogram normalization schemes, so they cannot be compared.  You can see this in another run [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-06-08_3&test=Nz_r_DEEP2_JAN&right=2018-06/2018-06-08_3/Nz_r_DEEP2_JAN/config.yaml).  However, note that in this case the errorbars on the simulation histogram actually seem a lot more reasonable!  So this justifies the conclusion above that the `normed=True` plots have a bug in the errorbar calculation.

**Comment by yymao** [comment]
I think the issue is that the normalization should be done after jackknife errors are calculated. I started my attempt to fix this in the [issue/117/Nz-normed-fix](https://github.com/LSSTDESC/descqa/tree/issue/117/Nz-normed-fix) branch. Will submit a PR once I have confirmed the fix works.
