### ISSUE TITLE
color cut in CLF test should work on catalogs that have redshift blocks

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#121]
[This issue](https://github.com/LSSTDESC/descqa/issues/50#issuecomment-399610103) that @evevkovacs encountered was due to the fact that the color cut implementation in the CLF test assumes the catalog does not iterate over redshift blocks. When a catalog iterates over redshift blocks, some blocks may not have the redshift ranges needed to determine the color cut, and hence results in error. 

This can be fixed if the test first determine the color cut using all blocks.

**Comment by evevkovacs** [comment]
Wouldn't it be sufficient to have the test read in the catalog using the iterator (as in the dN/dz test)? This modification will have to be made for the test to work on cosmoDC2 in any case.

**Comment by yymao** [comment]
Sorry if I wasn't clear. The test is already using the iterator feature. However, it assumes that in each dataset that is being iterated over, low-z objects always exist. This is not the case for the cosmoDC2 reader as some datasets contain only high-z objects, and hence results in the test to break.

I'll fix this on Monday.
