### ISSUE TITLE
Using COSMOS ellipticity distribution to validate catalogs

### ISSUE THREAD

**Issue by cosmicshear** [LSSTDESC/descqa#133]
I was looking at one of the DESCQA runs [here](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-02-26&test=ellipticity_dist_COSMOS&right=2018-02/2018-02-26/ellipticity_dist_COSMOS/protoDC2/Nvse2_m_i_M_V.txt) and was wondering if it is possible to have the actual COSMOS catalog to test the scaling of the ellipticity distribution with type and luminosity (using more absolute magnitude bins and different magnitude cuts).

**Comment by yymao** [comment]
@cosmicshear can you elaborate a bit more? Are you suggesting making a ellipticity-luminosity (with splitting on type) test, similar to [what we did in the size-luminosity test](https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-07-18_2&test=size_Mandelbaum2014_BD)? Note that the current ellipticity distribution test also use the COSMOS catalog directly (though we didn't keep the luminosity information).

**Comment by cosmicshear** [comment]
@yymao yes, something similar. I know that the current ellipticity distribution test already uses the COSMOS catalog, but I would like to have access to that catalog in order to test the mock catalogs in different absolute magnitude bins, redshift bins, magnitude cuts etc.

**Comment by yymao** [comment]
@cosmicshear the data that we used in the ellipticity test be found [here](https://github.com/LSSTDESC/descqa/tree/master/descqa/data/ellipticity/COSMOS/joachimi_et_al_2013). @evevkovacs compiled these data files so she can say more about them. As I mentioned, the luminosity information is not there yet, and I will hesitate to check in more raw data into descqa repo. I think we should just check in reduced data (we can also checking the code to reduce data into the `descqagen` folder).
