### ISSUE TITLE
Update CheckColors test to be compatible with DM outputs

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/descqa#141]
As it is now, the test checks for `mag_lsst`. We can do a quick update to CheckColors so it is compatible with the DM outputs.

**Comment by yymao** [comment]
I happen to know that @evevkovacs is working on updating this test. @evevkovacs, by any chance you can also address this issue in the PR you're about to submit?

**Comment by fjaviersanchez** [comment]
@yymao @evevkovacs I made a quick update in my fork (I added two lines of code) for the current test to be compatible with the dc2 object catalogs. If you are interested I can open a PR and solve this immediate issue. And after this, @evevkovacs can continue developing her updates. How does that sound? Or would you prefer to go the other way around (that @evevkovacs opens her PR and then we address this issue)?

**Comment by yymao** [comment]
@fjaviersanchez If it's a rather simple change I think you can open a PR and we can get it merge, and ask @evevkovacs to merge or rebase master.

**Comment by evevkovacs** [comment]
@yymao @fjaviersanchez  I am ready to do a PR for my changes also. All I did was add 2 lines. I just pushed my changes to the branch "test_mods" and submitted a  PR

**Comment by yymao** [comment]
closed by #142
