### ISSUE TITLE
validate instance catalogs to filter out offending AGN 

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#152]
Some AGNs are excessively bright and cause issues in image simulation, hence, we should implement a validate test to filter out the instance catalogs that contain offending AGNs (`magNorm` being too small). 

We can apply the test to `/global/projecta/projectdirs/lsst/production/DC2/Run1.2p/phosimInput/`

One example of instance catalog that contains offending AGNs is `DC2-R1-2p-WFD-u/000054/`. 

(cc @katrinheitmann)

**Comment by aphearin** [comment]
Is the cause of this error known? Is it due to the underlying black hole being unphysically massive or having unrealistically large accretion rate? Or is this due to a problem in the AGN model that gets applied on top of the black hole?

**Comment by katrinheitmann** [comment]
@danielsf would have to answer this question. I don't remember ... I am also not sure if it was addressed explicitly in the new AGN model. There is a whole long github issue here: https://github.com/LSSTDESC/DC2-production/issues/55 (which btw wonderfully demonstrates my problem with github in the way we are using it ... finding a final conclusion quickly from that is for the non-expert who was not deeply involved in the discussion impossible). We do want to make sure however that we inspect the AGNs explicitly before the run, even if it was supposedly fixed.
