### ISSUE TITLE
Verification Test to expose catalog meta-data 

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/descqa#16]
Users should have a way to query the meta-data to find out definitions such as the ellipticity definition  etc., or just to see what meta-data is available.

**Comment by yymao** [comment]
@evevkovacs this sounds like a feature of the GCR/GCRCatalogs rather than DESCQA?

**Comment by evevkovacs** [comment]
Yes, but it could go into another output file that gets produced by the 
list_quantities test..just like the yaml documentation. I think it would 
be handy.


On Mon, 6 Nov 2017, Yao-Yuan Mao wrote:

> Date: Mon, 6 Nov 2017 12:24:49
> From: Yao-Yuan Mao <notifications@github.com>
> Reply-To: LSSTDESC/descqa
>     <reply+0076fc4d0cae04ed1c68b999b852c0778472538ae262687892cf0000000116186af
>     192a169ce102fde2f@reply.github.com>
> To: LSSTDESC/descqa <descqa@noreply.github.com>
> Cc: Eve Kovacs <kovacs@anl.gov>, Mention <mention@noreply.github.com>
> Subject: Re: [LSSTDESC/descqa] Verification Test to expose catalog meta-data
>     (#16)
> 
> 
> @evevkovacs this sounds like a feature of the GCR/GCRCatalogs rather than DESCQA?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.[AHb8TQqiWA2DoQaqWVESvZT42br1nABHks5sz07xgaJpZM4QTqii.gif]
> 
> 
>

***************************************************************
Eve Kovacs
Argonne National Laboratory,
Room L-177, Bldg. 360, HEP
9700 S. Cass Ave.
Argonne, IL 60439 USA
Phone: (630)-252-6208
Fax:   (630)-252-5047
email: kovacs@anl.gov
***************************************************************

**Comment by yymao** [comment]
@evevkovacs Can you elaborate? Currently, anything that are specified in the yaml config can be accessed by the validation tests or by the users through interactive interface. So I am not sure what this particular issue's goal.

**Comment by evevkovacs** [comment]
People have asked about the definition of ellipticity for example, which should be included in the meta-data as should the shear sign convention. This 'test'  would print out that meta data in a file so that people could see it easily.

**Comment by yymao** [comment]
I see. This feature should be implemented in GCRCatalogs. I've opened an issue https://github.com/LSSTDESC/gcr-catalogs/issues/16 and will close this one.
