### ISSUE TITLE
Python Environment Name Change stack => desc

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/descqa#199]
In the most recent `desc-python` production release, the environment name was changed from `stack` to `desc`.  `desc-python` really has nothing to do with the DMstack and the environment name was confusing.

This impacts any scripts that are expecting to find an env named `stack`, such as here: 
https://github.com/LSSTDESC/descqa/blob/53f5cbf6be531c5d8cc08396517f6bfe2a22e3b2/run_master.sh#L10

**Comment by yymao** [comment]
fixed by c5b3529559abb69766562afd1ca2c01c7dfa2ed4
