### ISSUE TITLE
Need to update versions of gsl and cray-fftw in run_master.sh

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/descqa#209]
See [Slack](https://github.com/LSSTDESC/descqa/blob/cd3e1e216fa5da76bb0dcf8d97a9267541c4fde4/run_master.sh#L10) and https://github.com/LSSTDESC/descqa/blob/cd3e1e216fa5da76bb0dcf8d97a9267541c4fde4/run_master.sh#L10

Would it be ok to just use the current default version of those or is it really better to specify a version and update this periodically?  I'd vote for making this generic.  I'll open a PR.

**Comment by heather999** [comment]
I'm confused though.. would we expect typical users to run `run_master.sh`?  I see:
`OUTPUTDIR="/global/cfs/cdirs/lsst/groups/CS/descqa/run/v2"`
https://github.com/LSSTDESC/descqa/blob/cd3e1e216fa5da76bb0dcf8d97a9267541c4fde4/run_master.sh#L17
They should at least modify that first?

**Comment by yymao** [comment]
Yes, we should update the module. 

Any DESCQA user can run `run_master.sh`. `/global/cfs/cdirs/lsst/groups/CS/descqa/run/v2` is the correct  output directory for all users as we want to keep all DESCQA output in one place for the web interface to display them.
