### ISSUE TITLE
DeltaSigma test failures

### ISSUE THREAD

**Issue by patricialarsen** [LSSTDESC/descqa#237]
Reporting a couple of minor issues and corresponding fixes to DeltaSigmaTest.py due to catalog and library updates

DeltaSigma test currently fails due to 
1. numpy not liking astropy units in one line 
`    np.savetxt(outfile, np.vstack((rp, gt)).T)`
gives an error, altering this to 
`    np.savetxt(outfile, np.vstack((rp.value, gt.value)).T)`
fixes it. 

2. In diffsky stellar_mass is provided rather than stellar_mass_disk and stellar_mass_bulge. The read-in and calculation of sm should be changed to something like 

            if 'stellar_mass' in catalog_instance.list_all_quantities():
                res = catalog_instance.get_quantities(['redshift_true', 'ra', 'dec', 'shear_1', 'shear_2',
                    'mag_true_i_sdss', 'mag_true_z_sdss','mag_true_g_sdss', 'mag_true_r_sdss', 'stellar_mass','Mag_true_g_sdss_z0','Mag_true_r_sdss_z0'])
                gr = res['Mag_true_g_sdss_z0'] - res['Mag_true_r_sdss_z0'] # larger number means redder
                sm = res['stellar_mass']       
            else:
                res = catalog_instance.get_quantities(['redshift_true', 'ra', 'dec', 'shear_1', 'shear_2',
                    'mag_true_i_sdss', 'mag_true_z_sdss','mag_true_g_sdss', 'mag_true_r_sdss', 'stellar_mass_bulge', 'stellar_mass_disk','Mag_true_g_sdss_z0','Mag_true_r_sdss_z0'])
                gr = res['Mag_true_g_sdss_z0'] - res['Mag_true_r_sdss_z0'] # larger number means redder
                sm = res['stellar_mass_bulge'] + res['stellar_mass_disk']
            
to fix this

**Comment by yymao** [comment]
fixed by #239
