### ISSUE TITLE
stellar mass function

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#49]
I know @evevkovacs is working on the SMF test so I opened this issue to track progress.

- [x] code to reduce mock data
- [x] code that works within DESCQA framework
- [x] validation data
- [ ] validation criteria

**Comment by yymao** [comment]
A SMF test with PRIMUS 2013 data is now available from the merged PR #51.

**Comment by rmandelb** [comment]
@janewman-pitt-edu @sschmidt23 @morriscb - was this test of the stellar mass function in DC2 intended for the photo-z working group?

I hope @yymao will correct me if I am wrong, but my understanding is that the test has been implemented currently without a validation criterion, so we just need a validation criterion to close this issue.  Might PZ be able to supply a validation criterion?  You can see the format of the test here:

https://portal.nersc.gov/project/lsst/descqa/v2/?run=2017-12-21_14&test=SMF_PRIMUS

it's implemented in redshift bins based on comparison with PRIMUS.

**Comment by yymao** [comment]
Yes, @rmandelb. This test is already implemented. We need a validation criterion. If the PZ WG would like to provide a different validation data set, we can do that too.

**Comment by evevkovacs** [comment]
@rmandelb @janewman-pitt-edu @sschmidt23 This test was implemented in DESCQA1 and I ported it to DESCQA2 because it was such a basic test. I added the PRIMUS data for the higher redshifts. It wasn't formally requested by any WG to my knowledge.

**Comment by janewman-pitt-edu** [comment]
No, PZ has little interest in the mass function.  I think it was for LSS.

I would be wary of PRIMUS constraints as the sample is highly incomplete and has a relatively high catastrophic redshift error rate.  Low-z constraints are almost certainly more useful (especially because they can probe below L*).

**Comment by rmandelb** [comment]
@slosar - can you confirm whether LSS would like to have a validation test of the stellar mass function for DC2?

If no, then I think we can safely dispense with this validation test for DC2 since it's not needed to support any working group's goals.  If yes, then we need to define validation criteria etc.

**Comment by janewman-pitt-edu** [comment]
Just a note -- if we don't do a stellar mass constraint (and I'd be happy not to, as unlike magnitudes stellar masses are not directly observable but rather rely on models/assumptions to infer), we do want to have some sort of dN/dmag or dN/dz test to make sure the numbers of objects are sane.

**Comment by rmandelb** [comment]
Yes, I agree.  I don't believe there is any thought that the dN/dz or dN/dmag test will disappear (despite the fact that the exact form of these is still being finalized).

**Comment by yymao** [comment]
Given that this is not a required test and it is already implemented (though without validation criteria). We can probably close this issue. Do you agree @rmandelb?

**Comment by rmandelb** [comment]
@yymao - I agree.  People can look at the plot, and that's it - we are done.  Thank you!
