### ISSUE TITLE
Add SEDs to readiness test

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/descqa#64]
@yymao  Please take a look at https://github.com/evevkovacs/descqa/blob/ready_SEDS/SED_test.ipynb
The distributions are not as unreasonable looking as I expected, if we convert the SEDs to magnitudes. I am thinking that we can add a keyword to the yaml file such as function: -2.5*np.log10, which tells the readiness test to first evaluate the function on the catalog data before plotting it or computing any other statistics.  What do you think?

**Comment by yymao** [comment]
@evevkovacs the current readiness has the option to plot and calculate the statistics of the quality after taking log. I know log luminosity is not magnitude but  they differ by only a constant factor.  Given that this test is just for bug finding, I think this would be good enough, no?

**Comment by evevkovacs** [comment]
Yes, that would be good enough.
