### ISSUE TITLE
Create tag for Run 1.1

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#65]
I'm going to create a tagged version of DESCQA for Run 1.1 (while the DESCQA is not directly used in the run, it documents the validation tests that the catalog going it has passed, so I think it is good to have a tagged version too.) 

Is there any issues/PRs should be resolved before we make this tag? Maybe #60 and #64? Do we think it is reasonable to close them before Friday? Or should we leave them for the next tag (i.e., not included in Run 1.1)?

**Comment by evevkovacs** [comment]
@yymao  @dkorytov Yes, I think we can finish those up. It would be helpful if the A_v and R_v additions could be pushed to the protoDC2 reader. Is there any chance of getting the SED quantities in the reader in the next day or so? If yes, it would also be helpful as the yaml file entries for the SED checks would not have to be changed. Right now, I am using the native quantities.

**Comment by yymao** [comment]
@evevkovacs the SED part is now ready in the reader (as long as @dkorytov approves it), but since the CatSim interface is still using native quantities, it probably doesn't matter for Run 1.1 (unless we want to revise that part too). 

Similar story for `A_v` and `R_v` --- even if we edit the catalog, we need to edit the CatSim interface so that it uses what's in the catalog. Question is whether we can finish this before Run 1.1... 

I should note this discussion is probably meant for https://github.com/LSSTDESC/gcr-catalogs/issues/71

**Comment by yymao** [comment]
@evevkovacs It's about time to create a tagged version for Run 1.1. I'd like to merge #66 before I create the tag. Is there anything you'd like to add to #66? If not, I'll go ahead and merge it. If you do, can you let me know when you'll able to push them to #66? Thanks!

**Comment by dkorytov** [comment]
I have the Rv and Av ready to go. I think that should be merged in before creating the tag.

**Comment by yymao** [comment]
@dkorytov can you submit a PR? And again, this should goes to https://github.com/LSSTDESC/gcr-catalogs
