### ISSUE TITLE
Consistency Check for Convergence and Magnification

### ISSUE THREAD

**Issue by evevkovacs** [LSSTDESC/descqa#68]
Since these are related, we should check that the shears, convergence and magnification are self consistent (within machine precision). The test is that magnification should be satisfy 
'1/magnification = (1-kappa)**2 - shear1**2 - shear2**2)'
(kappa = convergence)

**Comment by rmandelb** [comment]
@evevkovacs - totally minor/irrelevant point but for people new to GitHub, I wanted to point out that you can use quote marks to avoid your math getting reinterpreted as GitHub markdown:
` 1/magnification = [(1-kappa)**2 - shear_1**2 - shear_2**2]`
And for reference to papers, magnification is often denoted mu, just as shear is often denoted gamma.

**Comment by yymao** [comment]
implemented in #66
