### ISSUE TITLE
shear sign convention test

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/descqa#8]
This is to test if the catalog follow the shear sign convention. 

- [ ] code to reduce mock data
- [ ] code that works within DESCQA framework
- [ ] validation data
- [ ] validation criteria

**Comment by EiffL** [comment]
The question is, what is the shear sign convention for LSST?

**Comment by yymao** [comment]
@EiffL that was why "has validation data" wasn't checked... 

@evevkovacs can you update us the status of sign convention?

**Comment by evevkovacs** [comment]
I am double-checking now...

On Mon, 6 Nov 2017, Yao-Yuan Mao wrote:

> Date: Mon, 6 Nov 2017 14:02:25
> From: Yao-Yuan Mao <notifications@github.com>
> Reply-To: LSSTDESC/descqa
>     <reply+0076fc4d3a65648a10ba06de2ea84307062d6def16b8121392cf00000001161881d
>     192a169ce102f2e8e@reply.github.com>
> To: LSSTDESC/descqa <descqa@noreply.github.com>
> Cc: Eve Kovacs <kovacs@anl.gov>, Mention <mention@noreply.github.com>
> Subject: Re: [LSSTDESC/descqa] shear sign convention test (#8)
> 
> 
> @EiffL that was why "has validation data" wasn't checked...
> 
> @evevkovacs can you update us the status of sign convention?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.[AHb8TX_8B5D50Ya1LxoZn03GhAdJmqhpks5sz2XRgaJpZM4QTd7J.gif]
> 
> 
>

***************************************************************
Eve Kovacs
Argonne National Laboratory,
Room L-177, Bldg. 360, HEP
9700 S. Cass Ave.
Argonne, IL 60439 USA
Phone: (630)-252-6208
Fax:   (630)-252-5047
email: kovacs@anl.gov
***************************************************************

**Comment by yymao** [comment]
@chihway, do you think you can help with this?

**Comment by chihway** [comment]
maybe, so here's what I know (from @rmjarvis, please confirm ):
* treecorr convention: you are the observer looking out towards the sky, the E-W direction is positive shear_1, the NE-SW direction is positive shear_2. This convention is also used by DES data.

* DC2 and buzzard convention: the same as above, except that you are in outer space looking down 

Between the above two conventions, you would need to flip shear_2 to make them consistent.

**Comment by rmjarvis** [comment]
Not quite.  NW-SE is positive shear_2.  West is to the right when looking up (and when north is up).

**Comment by yymao** [comment]
Also looping in catalog providers @j-dr and @dkorytov

**Comment by j-dr** [comment]
Can confirm that shear_1_buzzard=shear_1_treecorr and shear_2_buzzard=-shear_2_treecorr.

**Comment by patricialarsen** [comment]
I've just noticed this issue, I think this could be covered by the shear-shear correlation functions test as flipping the shear_2 sign alters the results for w-minus. I currently assume the buzzard/DC2 convention, if a catalog's shear_2 sign does not match this it should fail the w-minus test and swapping the sign should fix this. 

It doesn't solve the question of what sign convention to use, but it should flag up if a catalog uses a different convention to the one we expect and it's a simple thing to add in.

**Comment by yymao** [comment]
According to @patricialarsen, I think we can close this since it will be covered in #35. 

@patricialarsen @rmandelb Feel free to reopen if you disagree.
